
import React from 'react';
import {
    PersonAdd,
    Login,
    Lock,
    CheckCircle,
    AddShoppingCart,
    Done,
    Straighten,
    DensityMedium,
    Tune,
    Paid,
    Engineering,
    TrendingUp,
    Bolt,
    ElectricMeter,
    Toll,
    Percent,
    Recycling,
    SwapHoriz,
    Key,
    Category,
    ReceiptLong,
    Inventory2,
    PendingActions,
    Print,
    NewReleases,
    Person,
    Logout,
    History,
    Menu,
    Close,
    Calculate,
    CalendarMonth,
    Mail,
    Instagram,
    WhatsApp,
    PhotoCamera,
    ThreeDRotation,
    Timer,
    Scale,
    Inventory,
    ViewInAr,
    Palette,
    Refresh
} from '@mui/icons-material';

interface IconProps {
    name: string;
    className?: string;
    style?: React.CSSProperties;
}

export const Icon: React.FC<IconProps> = ({ name, className, style }) => {
    const icons: Record<string, React.ReactNode> = {
        person_add: <PersonAdd className={className} style={style} />, 
        login: <Login className={className} style={style} />, 
        lock: <Lock className={className} style={style} />, 
            add_shopping_cart: <AddShoppingCart className={className} style={style} />,
            done: <Done className={className} style={style} />,
            straighten: <Straighten className={className} style={style} />,
            density_medium: <DensityMedium className={className} style={style} />,
            tune: <Tune className={className} style={style} />,
            paid: <Paid className={className} style={style} />,
            engineering: <Engineering className={className} style={style} />,
            trending_up: <TrendingUp className={className} style={style} />,
            bolt: <Bolt className={className} style={style} />,
            electric_meter: <ElectricMeter className={className} style={style} />,
            toll: <Toll className={className} style={style} />,
            percent: <Percent className={className} style={style} />,
            recycling: <Recycling className={className} style={style} />,
            swap_horiz: <SwapHoriz className={className} style={style} />,
            key: <Key className={className} style={style} />,
            category: <Category className={className} style={style} />,
            receipt_long: <ReceiptLong className={className} style={style} />,
            inventory_2: <Inventory2 className={className} style={style} />,
            pending_actions: <PendingActions className={className} style={style} />,
            print: <Print className={className} style={style} />,
            new_releases: <NewReleases className={className} style={style} />,
            person: <Person className={className} style={style} />,
            logout: <Logout className={className} style={style} />,
            history: <History className={className} style={style} />,
            menu: <Menu className={className} style={style} />,
            close: <Close className={className} style={style} />,
            calculate: <Calculate className={className} style={style} />,
            calendar_month: <CalendarMonth className={className} style={style} />,
            mail: <Mail className={className} style={style} />,
            instagram: <Instagram className={className} style={style} />,
            whatsapp: <WhatsApp className={className} style={style} />,
            photo_camera: <PhotoCamera className={className} style={style} />,
            "3d_rotation": <ThreeDRotation className={className} style={style} />,
            timer: <Timer className={className} style={style} />,
            scale: <Scale className={className} style={style} />,
            inventory: <Inventory className={className} style={style} />,
            view_in_ar: <ViewInAr className={className} style={style} />,
            palette: <Palette className={className} style={style} />,
        refresh: <Refresh className={className} style={style} />,
        check_circle: <CheckCircle className={className} style={style} />
        };
        return icons[name] || <span className={className} style={style}>{name}</span>;
};
